# Generated by Django 5.1 on 2024-11-06 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TienNghi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HoSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dien_thoai', models.CharField(max_length=10)),
                ('dia_chi', models.CharField(max_length=200)),
                ('ngay_sinh', models.DateField(blank=True)),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=6)),
                ('cccd', models.CharField(max_length=12)),
                ('vai_tro', models.CharField(choices=[('Khách thuê', 'Khách thuê'), ('Khách sạn', 'Khách sạn')], default='Khách thuê', max_length=15)),
                ('nguoi_dung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KhachSan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=150)),
                ('hinh_anh1', models.ImageField(upload_to='hotel_images/')),
                ('hinh_anh2', models.ImageField(upload_to='hotel_images/')),
                ('hinh_anh3', models.ImageField(upload_to='hotel_images/')),
                ('dia_chi', models.CharField(max_length=250)),
                ('lien_he', models.CharField(max_length=10)),
                ('web_site', models.URLField(max_length=255)),
                ('mo_ta', models.TextField()),
                ('chu_khach_san', models.OneToOneField(limit_choices_to={'hoso__vai_tro': 'Khách sạn'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=50)),
                ('hinh_anh1', models.ImageField(upload_to='room_images')),
                ('hinh_anh2', models.ImageField(upload_to='room_images')),
                ('hinh_anh3', models.ImageField(upload_to='room_images')),
                ('gia', models.IntegerField()),
                ('suc_chua', models.IntegerField()),
                ('mo_ta', models.TextField()),
                ('khach_san', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tien_nghi', models.ManyToManyField(to='booking.tiennghi')),
            ],
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sao', models.IntegerField()),
                ('content', models.TextField()),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.phong')),
            ],
        ),
    ]
