# Generated by Django 5.1 on 2024-11-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_danhgia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khuyenmai',
            name='ma_km',
        ),
        migrations.AddField(
            model_name='datphong',
            name='yeu_cau',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='khachsan',
            name='trang_thai',
            field=models.CharField(choices=[('Đang hoạt động', 'Đang hoạt đông'), ('Ngừng hoạt đông', 'Ngừng hoạt động')], default='Đang hoạt động', max_length=30),
        ),
        migrations.AlterField(
            model_name='datphong',
            name='trang_thai',
            field=models.CharField(choices=[('Chờ xác nhận', 'Chờ xác nhận'), ('Đã hủy', 'Đã hủy'), ('Đã xác nhận', 'Đã xác nhận'), ('Đã hoàn thành', 'Đã hoàn thành')], default='Chờ xác nhận', max_length=30),
        ),
    ]
