# Generated by Django 5.1 on 2024-11-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_khuyenmai_ma_km_datphong_yeu_cau_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khachsan',
            old_name='lien_he',
            new_name='dien_thoai',
        ),
        migrations.RenameField(
            model_name='khachsan',
            old_name='web_site',
            new_name='website',
        ),
        migrations.AddField(
            model_name='khachsan',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
