# Generated by Django 5.1 on 2024-11-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_rename_lien_he_khachsan_dien_thoai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachsan',
            name='ngay_tao',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
