# Generated by Django 5.1 on 2024-11-14 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_khachsan_ngay_tao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiennghi',
            name='khach_san',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.khachsan'),
        ),
        migrations.AlterField(
            model_name='khachsan',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='khachsan',
            name='ngay_tao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
