# Generated by Django 5.1 on 2024-11-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_khuyenmai_ngay_ket_thuc_alter_khuyenmai_phong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datphong',
            name='so_khach',
            field=models.IntegerField(default=1),
        ),
    ]
