# Generated by Django 5.1 on 2024-11-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_rename_chu_the_datphong_ngan_hang'),
    ]

    operations = [
        migrations.AddField(
            model_name='datphong',
            name='thoi_gian',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
